### ISSUE TITLE
Unknown identifier 'g_tsu' and etc.

### ISSUE THREAD

**Issue by Oleksandr32** [aaruelschool/Serpent-Implementation#1]
Hi, great work.
I have noticed that few files has missing time generic constants, for example, 'g_tsu', 'g_th' , 'g_tpd'...

![image](https://user-images.githubusercontent.com/24620659/80540136-68483200-89b1-11ea-9eaa-e92230939064.png)

maybe you forgot to push them or could you explain how can I  create them?

**Comment by aaruel** [comment]
updated with those constants and the components from the gatelib I was using, I think that's all, I excluded them for a reason at the time :+1:

**Comment by Oleksandr32** [comment]
Nice, it works perfect.
Thanks so much.
I will close this issue.
